import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { createSqlJournal, type JournalDatabase } from '../../src/storage/sqlJournal.ts';
import type { ClipFileMetadata, ClipIntent, ClipVault } from '../../src/storage/clipTypes.ts';
import type { Moment } from '../../src/storage/types.ts';

export const intent: ClipIntent = { id: 'clip-1', momentId: 'moment-1', createdAt: '2026-09-21T10:00:00.000Z' };
export function moment(id = 'moment-1'): Moment {
  return { id, emotionId: 'fomo', emotionLabel: 'FOMO', createdAt: intent.createdAt, supportText: 'Synthetic test moment.' };
}

// NOT encryption or a security proof: generated bytes in JSON, with an unkeyed
// checksum only to model the native adapter's owner/integrity rejection contract.
export class FixtureVault implements ClipVault {
  failures = new Set<string>();
  metadata?: ClipFileMetadata;
  onSeal?: () => Promise<void>;
  readonly root: string;
  constructor(root: string) { this.root = root; }
  path(id: string, kind: 'staging' | 'final' | 'playback') {
    if (!/^[a-z0-9-]{1,64}$/.test(id)) throw new Error('unsafe fixture ID');
    return join(this.root, `${id}.${kind}`);
  }
  seed(owner: ClipIntent, kind: 'staging' | 'final' | 'playback' = 'staging') {
    const data = Buffer.alloc(16, 42).toString('hex');
    writeFileSync(this.path(owner.id, kind), JSON.stringify({ ...owner, data, durationMs: 1000, digest: createHash('sha256').update(data).digest('hex') }));
  }
  private fail(operation: string, id: string) {
    if (this.failures.has(`${operation}:${id}`)) throw new Error('private/path native key material');
  }
  async seal(owner: ClipIntent): Promise<ClipFileMetadata> {
    this.fail('seal', owner.id);
    await this.onSeal?.();
    const final = this.path(owner.id, 'final');
    const source = existsSync(final) ? final : this.path(owner.id, 'staging');
    const raw = readFileSync(source, 'utf8');
    const file = JSON.parse(raw);
    if (file.id !== owner.id || file.momentId !== owner.momentId || file.createdAt !== owner.createdAt ||
        file.digest !== createHash('sha256').update(file.data).digest('hex')) throw new Error('private/path invalid fixture');
    if (!existsSync(final)) writeFileSync(final, raw, { flag: 'wx' });
    return this.metadata ?? { bytes: Buffer.from(file.data, 'hex').length, durationMs: file.durationMs };
  }
  async removeStaging(owner: ClipIntent) {
    this.fail('staging', owner.id);
    rmSync(this.path(owner.id, 'staging'), { force: true });
  }
  async removeAll(owner: ClipIntent) {
    this.fail('all', owner.id);
    for (const kind of ['staging', 'final', 'playback'] as const) rmSync(this.path(owner.id, kind), { force: true });
  }
}

export async function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'still-clip-test-'));
  let sqlite = new DatabaseSync(join(root, 'journal.db'));
  let fault: ((sql: string) => void) | undefined;
  const driver = (): JournalDatabase => ({
    async execAsync(sql) { fault?.(sql); sqlite.exec(sql); },
    async runAsync(sql, ...params) { fault?.(sql); return sqlite.prepare(sql).run(...params); },
    async getAllAsync<T>(sql: string, ...params: string[]) {
      fault?.(sql);
      return sqlite.prepare(sql).all(...params).map(row => ({ ...row })) as T[];
    },
  });
  let db = driver();
  const legacy = await createSqlJournal(db);
  await legacy.save(moment());
  let vault = new FixtureVault(root);
  return {
    root, legacy,
    get sqlite() { return sqlite; },
    get db() { return db; },
    get vault() { return vault; },
    inject(next?: (sql: string) => void) { fault = next; },
    reopen() {
      sqlite.close();
      sqlite = new DatabaseSync(join(root, 'journal.db'));
      db = driver(); vault = new FixtureVault(root); fault = undefined;
    },
    close() {
      sqlite.close();
      if (dirname(resolve(root)) !== resolve(tmpdir()) || !root.startsWith(join(tmpdir(), 'still-clip-test-'))) {
        throw new Error('Refusing cleanup outside fixture temp root');
      }
      rmSync(root, { recursive: true, force: true });
    },
  };
}
